name: 'Deploy Files to Remote Server'
description: 'Upload files to a remote server using specified configurations and execute commands'
inputs:
  server-ip:
    description: 'IP address of the remote server'
    required: true
  server-user:
    description: 'Username for the remote server'
    required: true
  server-password:
    description: 'Password for the remote server'
    required: true
  remote-path:
    description: 'Path to upload files on the remote server'
    required: true
  files:
    description: 'List of files and folders to upload, separated by commas'
    required: true
  cmd:
    description: 'Optional command to execute after upload'
    required: false
  jump-ip:
    description: 'Jump server IP address (optional)'
    required: false
  jump-user:
    description: 'Jump server username (optional)'
    required: false
  jump-password:
    description: 'Jump server password (optional)'
    required: false
runs:
  using: 'node20'
  main: 'lib/index.js'